name: Run Pokemon Price Tracker

on:
  workflow_dispatch:

  schedule:
    - cron: "0 8 * * *"

permissions:
  contents: read

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tracker
        env:
          EBAY_CLIENT_ID: ${{ secrets.EBAY_PROD_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_PROD_CLIENT_SECRET }}
          BUYER_POSTCODE: ${{ secrets.BUYER_POSTCODE }}
        run: python tracker.py
