name: Run Pokemon Price Tracker

on:
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tracker
        env:
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
        run: python tracker.py
